### ISSUE TITLE
현재 컨트롤러 액션을 누구나 실행가능함

### ISSUE THREAD

**Issue by limdongjin** [gmlwls/old_books#7]
comments replies notification 컨트롤러같은경우에 액션을 아무나 실행할수있는 상황임. 
( 비로그인 회원, 본인이 아닌 상황에서 댓글삭제, 알림삭제, 생성)

**Comment by pixar0407** [comment]
authenticate_user역시 해당 controller 명시하겠음.
comment 와 replies 삭제 백엔드 단에서 user 선별적
